import { schema } from '@ioc:Adonis/Core/Validator'
import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export default class InfortecnicaValidator {
  constructor (protected ctx: HttpContextContract) {
  }

  public schema = schema.create({
	id_receita: schema.string(),
	aplicacao: schema.string.optional({trim: true}),
	areatratar: schema.string({trim: true}),
	classetoxico: schema.string.optional({trim: true}),
	classificacaocultura: schema.string.optional({trim: true}),
	codcultura: schema.string({trim: true}),
	concentracao: schema.string.optional({trim: true}),
	dosagem: schema.string({trim: true}),
	epi: schema.string.optional({trim: true}),
	epocaaplicacao: schema.string.optional({trim: true}),
	estagiocultura: schema.string.optional({trim: true}),
	fitoxidade: schema.string.optional({trim: true}),
	formulacao: schema.string.optional({trim: true}),
	horario: schema.string.optional({trim: true}),
	nomeembalagem: schema.string({trim: true}),
	tipoembalagem: schema.string({trim: true}),
	unidademmbalagem: schema.string({trim: true}),
	indicacao: schema.string.optional({trim: true}),
	ingredienteativo: schema.string.optional({trim: true}),
	intervaloaplicacao: schema.string.optional({trim: true}),
	intervaloentrada: schema.string({trim: true}),
	intervaloseguranca: schema.string.optional({trim: true}),
	lote: schema.string.optional({trim: true}),
	id_agrotoxico: schema.number(),
	id_cultura: schema.number(),
	modaplicacao: schema.string({trim: true}),
	modoaplicacao: schema.string({trim: true}),
	nomeagrotoxico: schema.string({trim: true}),
	nomecultura: schema.string({trim: true}),
	nomeclasse: schema.string.optional({trim: true}),
	nomeclasseambiental: schema.string.optional({trim: true}),
	nomegrupoquimico: schema.string.optional({trim: true}),
	numeroaplicacoes: schema.string.optional({trim: true}),
	problemacientifico: schema.string({trim: true}),
	problemacomum: schema.string({trim: true}),
	quantembal: schema.string({trim: true}),
	quantidadeadquirir: schema.string({trim: true}),
	registroagrotoxico: schema.string.optional({trim: true}),
	tipoaplicacao: schema.string.optional({trim: true}),
	volumecalda: schema.string({trim: true}),
	volumecaldabula: schema.string({trim: true}),
	dosagembula: schema.string({trim: true}),
	solo: schema.string.optional({trim: true}),
  })

	
  public messages = {
	'id_receita.required': 'Selecione uma receita para adicionar um produto',
	'areatratar.required': 'Área a tratar deve ser preenchido',
	'codcultura.required': 'Obrigatório informar o código da cultura',
	'dosagem.required': 'Obrigatório informar a desagem',
	'nomeembalagem.required': 'Obrigatório informar o nome da embalagem',
	'tipoembalagem.required': 'Obrigatório informar o tipo da embalagem',
	'unidademmbalagem.required': 'Obrigatório informar a unidade da embalagem',
	'intervaloentrada.required': 'Obrigatório informar o intervalo de entrada',
	'id_agrotoxico.required': 'Obrigatório informar o ID do agrotoxico',
	'id_cultura.required': 'Obrigatório informar o ID da cultura',
	'modaplicacao.required': 'Obrigatório informar o modo de aplicação',
	'modoaplicacao.required': 'Obrigatório informar o modo de aplicação',
	'nomeagrotoxico.required': 'Obrigatório informar o nome do agrotoxico',
	'nomecultura.required': 'Obrigatório informar o nome da cultura',
	'problemacientifico.required': 'Obrigatório iformar o problema cientifico',
	'problemacomum.required': 'Obrigatório iformar o problema cientifico',
	'quantembal.required': 'Obrigatório informar a quantidade da embalagem',
	'quantidadeadquirir.required': 'Obrigatório informar a quantidade a ser adquirida',
	'volumecalda.required': 'Obrigatório informar o volume de calda',
	'volumecaldabula.required': 'Obrigatório informar o volume de calda',
	'dosagembula.required': 'Obrigatório informar a dosagem',
  }
}
